version: "3.8"

services:
  database:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - uba_intern

  backend:
    depends_on: 
      - database
    restart: unless-stopped
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      TEST_PORT: ${TEST_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SECRET: ${SECRET}
      URL: ${URL}
    networks:
      - uba_intern

networks:
  uba_intern:
    driver: bridge

volumes:
  db:
